### ISSUE TITLE
Add smoothing to new cases chart

### ISSUE THREAD

**Issue by ndri** [koroonakaart/koroonakaart#102]
Currently, the new cases chart is chaotic and hard to draw any conclusions from. 

Would it be possible to add an option to add smoothing to the chart? The option would allow data points to be recalculated to the averages of surrounding days. Example below.

Before smoothing - current chart:
![Before smoothing](https://user-images.githubusercontent.com/5224431/78715908-bb851280-7926-11ea-9d4c-88c92d14b64b.png)

After smoothing - new values are averages of surrounding 3 days on both sides:
![After smoothing](https://user-images.githubusercontent.com/5224431/78715985-d9eb0e00-7926-11ea-87dc-33709c5fd199.png)

**Comment by keeganmcbride** [comment]
Theoretically we could add this as a tab/button option for the chart, will take a look.

**Comment by priitpavelson** [comment]
NY Times uses 7-day average for smoothing the graph https://www.nytimes.com/interactive/2020/world/coronavirus-maps.html
You may keep the bars but add an average line to it.

**Comment by neuroactive** [comment]
Rather than changing data points based on their neighbours, which makes it impossible to see the true figures for any specific day, it would be preferable to handle this by adding a trendline showing the 7-day average, as mentioned by Priit and as already suggested in #92. So I will close this issue in favour of that one.
