### ISSUE TITLE
Recovered people ?

### ISSUE THREAD

**Issue by kaheksa** [koroonakaart/koroonakaart#104]
The infection number is rising, but where is the number of recovered people?
We only have the "out of hospital" number and no true active case number. Are the active cases around 1100 or is it 700 or 300 ? Most people are sick for about a week or two and then fine.

or is nobody checking up on the at home active cases? :)

**Comment by mmarx83** [comment]
Ja see statistika võiks olla samuti maakondade lõikes :) see on kummaline tegelikult et tervenenute hulgast Eestis sõnagi ei räägita.

**Comment by maxml76** [comment]
Statistiliselt vist sellest viisusest paranemist loota pole?
1300+ haigestumist 1,5  kuu jooksul ja ei ühtegi tervenenut?

**Comment by keeganmcbride** [comment]
The issue here is, per usual, with data. It is not available, unfortunately. If TEHIK or TA is able to make it available then we will put it online. I agree that it is a bit frustrating that we have no indication of how many cases are active or not, it is not possible to track recovery at all in Estonia right now.

**Comment by kaups007** [comment]
They start to talk about that more and more, cumulative number is actually not that actual. 
Maybe there is a reason for "propably recovered" line in koroonakaart charts?

So if we take from 2. april....  1434-959= 473 active cases now.

https://www.delfi.ee/news/paevauudised/eesti/graafik-tooriist-et-tegelikku-koroonahaigete-hulka-arvutada-nakatunute-arv-ei-kasva-ega-kahane-vaid-pusib-stabiilsena?id=89581611

**Comment by kaheksa** [comment]
So a rough estimate would be that people declared "active" more than 3 weeks ago are now "recovered". There is a small number in there that are in the hospital with a hard case, but thats ok.

I would love to see this implemented in the data shown and should be easy to do also

**Comment by keeganmcbride** [comment]
I talked with TEHIK and they told me this data should be coming, so hopefully in the next week or so I can update it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dominique-unruh** [comment]
I see that the charts now estimate the active cases by assuming that new confirmed cases go away after two weeks. Is that an "official" counting method (i.e., from the health board or similar), or a choice by the developers of the web page?

**Comment by keeganmcbride** [comment]
Not official, still no new data has come yet, this is an estimate that has now started to appear in other media channels, so we have added it as well. It is, as you wrote, the current cases at a given time minus all cases that occurred two weeks prior, this is why we call it estimated active cases and not active cases. I hope that at some point soon better data is released so that we can improve upon this estimate. 

See in media, for ex:

https://www.delfi.ee/news/paevauudised/eesti/graafik-tooriist-et-tegelikku-koroonahaigete-hulka-arvutada-nakatunute-arv-ei-kasva-ega-kahane-vaid-pusib-stabiilsena?id=89581611

https://www.postimees.ee/6958245/koroonahaiguse-podejate-arv-kukkus-kahe-nadalaga-enam-kui-kaks-korda

**Comment by dominique-unruh** [comment]
It's a sensible way of estimating (at least to a nonexpert like me), but perhaps it would be good to augment the FAQ entry "Where does the data come from?" to indicate that not all the data is directly from TEHIK? Just to avoid misunderstandings. :)

**Comment by keeganmcbride** [comment]
Yes, I will amend the FAQ section, it is a good point. Thank you.
