### ISSUE TITLE
Stacked column chart for new cases per county

### ISSUE THREAD

**Issue by ndri** [koroonakaart/koroonakaart#124]
Currently, there is a cumulative line chart for total cases per county. I often find myself looking for which counties got new cases in the previous day. This is annoying to do on a line chart and would be easier on a stacked column chart.

Example:
![Stacked column chart for new cases per county](https://i.imgur.com/i9sYSql.png)

**Comment by sarnane** [comment]
Hello!

I've started working on this. Should be ready in a day or two.

**Comment by neuroactive** [comment]
@sarnane Many thanks for the pull request. The chart looks great and I have sent it live.

The only very minor issue I found is that there was no space showing in the tooltip between the county name and the number of cases, but I have fixed that by replacing the existing space in the code with a non-breaking space.

In general, I think we could improve the style of the dates in the x-axis labels so that they are in a more easily readable format and properly localised, but I will open a separate issue for that.
