### ISSUE TITLE
Ettepanek (info@okee.ee kaudu) võiks olla ka aktiivsete haigusjuhtude hinnang 10 000 elaniku kohta maakonniti

### ISSUE THREAD

**Issue by infokujur** [koroonakaart/koroonakaart#137]

**Comment by infokujur** [comment]
Nüüd klikkisin kaardil ja see olemas. Pardoon :).

**Comment by infokujur** [comment]
Ja kui pea ei jookse, siis jalad peavad ....

Ehk nagu aru saan, siis on praegu olemas **Aktiivsete haigusjuhtude arv** (absoluut) ning siis on kogu ajalooline data **Absoluutarv** ning selle jaotumine **10 000 elaniku kohta**?

Sellisel juhul soovitakse neljandat juurde, mis oleks Aktiivsete haigusjuhtude arv 10 000 elaniku kohta.

**Comment by keeganmcbride** [comment]
It would be a bit challenging to do the map for the active cases as we have only ranges for the given municipalities rather than individual cases by municipality. As there is not much development work going on right now, I don't foresee this being implemented.

**Comment by jaanus** [comment]
Just a moment ago I was looking at the map which shows cases per 10 000 people per country. Saaremaa is darkest blue and shows the highest number because of the local outbreak months ago. Today, this is not really relevant and helpful information, you could say it is misleading. It is historically interesting but not that relevant today or over longer time.

I don’t have a good proposal for what to do with the map here, I don’t know what data is available per county over time. Just this number across whole history is less and less valuable over longer time. It should have some time/freshness aspect to it. And/or make it more clear with the labeling and presentation what is “current” and what is “for all time”, it is hard to tell these two categories of info apart with the map.

**Comment by infokujur** [comment]
Maybe some date filter can improve this?

**Comment by Imret** [comment]
As a frequent viewer of the koroonakaart, I would really like to see a fourth link displaying active cases per 100,000 people per county (Viimase 14 päeva nakatumised 100 000 inimese kohta maakonniti). There already is an Active cases estimate for the map and all we need now is to divide the Active cases estimate by the population of the county and multiply by 100,000, that's it!

**Comment by keeganmcbride** [comment]
I will look into making this today/tomorrow, thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by keeganmcbride** [comment]
@Imret I pushed a working proof of concept to the live version. Now the current infection rate per 100k pop over the past 14 days may be viewed on the map. I will work a bit more on improving how it looks for mobile / extending it into a graph in the coming days.

**Comment by Imret** [comment]
@keeganmcbride I noticed the new option - looks awesome! That's the most useful feature of this map for me.

**Comment by jaanus** [comment]
"Viimase 14 päeva nakatumised 100 000 inimese kohta" on the map looks and works really great. 👍 Looks and works OK on my iPhone too.
