### ISSUE TITLE
Hypocrisy detected

### ISSUE THREAD

**Issue by solkmaaker** [koroonakaart/koroonakaart#163]
Since you have closed koroonakaart.ee as you say: "However, as project manager, a foreigner, and supporter of LGBTQ rights, I can no longer keep this site up and running in support of a government that does not uphold the Estonian constitution or help to create a more tolerant and accepting society."

You as a foreign citizen did reserve yourself a right to close service because you disagreed with somebody's opinion.
In this case it was government of foreign country.
How would you feel if you were denied of services based on your opinions? Because this is exactly what you did.
This is very narrow-minded and hypocritical behavior from your side.

**Comment by manuganji** [comment]
Thanks for your service. If it was your right to build and offer a voluntary solution, it is also your right to stop offering it.

I'm sorry for your hurt.

**Comment by solkmaaker** [comment]
Well, voluntary or not, this is hypocrisy nevertheless.
Accelerate Estonia, Garage48 and Open Knowledge Estonia do not operate from thin air, in this case Open Knowledge Estonia received funds from ministry of economic affairs and communications.

I can understand difference of opinions. Closing service is also OK for whatever reason.
But to emphasize that this is due to disagreement is same if government would deny you services based to your opinions.
Further more, Estonia is democratic state and even government opinion does not mean anything unless it follows direct actions, which have not happened. And according to democracy, the LGBT+ issue that mr. McBride referrers to will be decided by majority of people in referendum.
This is how democracy works, not: i'm closing service because you have "wrong" opinions.

**Comment by emercer** [comment]
Interesting. I wonder if @solkmaaker feels the same about Estonia's failure to implement the criminalization of hate speech, which was democratically decided by all member states of the European Parliament, where Estonia holds seven seats. It has committed to codify these laws in 2008 and still has not done so, in a breach of European democracy. But apparently, in the views of our Minister of Interior and our Finance Minister, being fined for undemocratic behavior by the European Commission is not a problem if it's to protect the right to expressing hate.

Anyways, Dr. McBride, thank you for your _voluntary_, **invaluable** service. It will be missed. Maybe people will hear.

**Comment by kaheksa** [comment]
Its open code. Someone copy it and but a new site up :)

**Comment by Zaaset** [comment]
During an onslaught of the second wave, you decided to disable a KEY health early warning service. Over a referendum next year. If this is not "whipping it out and shove it in your face", I don't know what is. You could have kept the service running. You could have put the message on the side. But you chose to nuke it.

Also, you did not write your message in Russian. (23/10/2020 build)

**Comment by dv** [comment]
@solkmaaker the service that McBride provided for free was supporting the government, since they are not shy to link to this site without paying for it. Apparently McBride disagrees with the government enough that he no longer wishes to support that same government. Following that reasoning, he took down the free service he provided. I don't see any issue with that, that is not hypocrisy.

To expect someone to offer their services for free to an entity they do not support is absurd.

The government is free to start paying someone to render the same service. If that person who got paid for it, then decides to take it down breaking their contract, that's another matter entirely. But that does not seem to be the case here.

@Zaaset if it's as critical as you suggest (and I don't disagree), then the government should have taken action already to secure this critical service, by either paying McBride or setting up something similar, instead of piggybacking on the voluntary efforts by McBride and the rest of the team. That they have not done so speaks to their competence. Your dissatisfaction should be aimed at the government for that failure, not at McBride for exercising his freedoms.

**Comment by mmeest** [comment]
Interesting.

If all the online services in the future would depend on all developers opinion in every time frame on every coverment's decisions, and actions.

**Comment by dv** [comment]
@mmeest that's right! I too am glad Estonia is a free nation where servitude has been abolished.

**Comment by AnkBurov** [comment]
This is very wrong to mix personal opinion of Mart Helme who is quite notorious for his eccentric statements with the opinion of the whole Estonian government.

**Comment by manuganji** [comment]
I also agree that one politician/party doesn't represent the whole of estonia and if the referendum is still pending, I would consider the popular will to still be unknown.

But I respect your right as a creator.

**Comment by clyde-johnston** [comment]
It is a disgrace that Dr McBride has chosen to withdraw this public service in the midst of a pandemic.  It is not about him, the Estonian government or any particular minister.  It is about informing the general public about an important health situation.  Whatever Dr McBride's views are on LGBT rights, they have absolutely nothing to do with this service.  Perhaps it was just an excuse to extricate himself from this project.

**Comment by dividedpixel** [comment]
> It is a disgrace that Dr McBride has chosen to withdraw this public service in the midst of a pandemic.

Utter nonsense.
 
@keeganmcbride as a private individual is not compelled to work for free on anything that they choose not to. If they feel that closing this site that they volunteered their time creating and running is the right course, then that is entirely their choice and no-one elses.

@clyde-johnston you are more than welcome to spend your time creating and running your own site providing this service, or even better, so could the current Estonian government. The real disgrace is that we are seven months into this pandemic and the government has not made any efforts to provide this service up til now and just leave it to volunteers to do instead.

**Comment by aldas** [comment]
Looking at commit log I assume that @keeganmcbride got very tired of this work and LGBT topic is manifestation of this frustration. 

Keeping [things up to date manually](https://github.com/okestonia/koroonakaart/blame/82e57402999c8cbb6f429e253249945245ce3b5a/TEHIK_Open_Data_Loading_Scripts/main.py#L18) multiple times per day (look at commit log) is quite a bit of work. No wonder he does not want to do it anymore.

this kind of tedious work could be made less of a chore with automation. For some data that does not have 'open data source' still needs to be updated. but building new artifacts and deploying new version can be automated to  'single' button click on github.  And if this frequently updated data is extracted to separate file maybe even not a programmer could edit those files in github file editor.

anyway. I added my help with #165  (building new version with Github actions and adding Docker support)

**Comment by AnkBurov** [comment]
@dividedpixel it's not exactly true. The government does have the similar website but with much worse UX https://www.terviseamet.ee/et/koroonaviirus/koroonakaart
They said they gonna translate this project to additional languages since the koroonakaart project is closed now. 
https://news.err.ee/1150529/coalition-stance-on-lgbtq-issues-prompts-koroonakaart-creator-to-close-site

@aldas oh, f. I would never thought that the website is updated manually (if this process is not automated ofc). It explains that sudden tantrum. :open_mouth:

**Comment by kaheksa** [comment]
Whats the visitor amount of the site anyway? Looking at how people look at covid now does anybody visit the site? 
I just look at the 14 day number sometimes to see if some travelban might get lifted. Havent looked at the rest of it since May.

Its just a random number that gets published daily that nobody really cares about anymore. Similar to "deaths in traffic" that you just see as a headline in Delfi.

Maybe it was just pointless to work on a site that nobody visited and this was a good excusse...

**Comment by dv** [comment]
You shouldn't try and spin this as anything other than what it says on the tin. If @keeganmcbride would have gotten tired of the work, they wouldn't have needed an excuse to just stop the site without making a statement like they did, or found someone to take over, or automate it using a solution like @aldas proposed. Your attempts to downplay their protest are childish.

**Comment by emercer** [comment]
> Whats the visitor amount of the site anyway? Looking at how people look at covid now does anybody visit the site?

denial and anger have given place to bargaining. By the end of the week we'll be on acceptance.

**Comment by KristianKalm** [comment]
> Its open code. Someone copy it and but a new site up :)

https://corona.ee/

edit: as the service is restored, this domain will redirect to it

**Comment by aldas** [comment]
@KristianKalm just deploying this to somewhere does not fix everything.  Numbers for  'intensive care' and 'deceased persons' 
are manually updated. See https://github.com/okestonia/koroonakaart/blob/125c9c735896427cca885d60791b3f7a84991edf/TEHIK_Open_Data_Loading_Scripts/main.py#L18

for it all to work there should be cron to rebuild frontend every day and dedicated persons to update those numbers on change. Unless TEHIK (Terviseameti itguys) will expose those numbers also as open data. Then only [cron](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onschedule) would be enought.

p.s. refresh https://corona.ee/et gives 404. Webserver is missing redirection to index.html. For Nginx something like that would help https://github.com/okestonia/koroonakaart/blob/125c9c735896427cca885d60791b3f7a84991edf/Dockerfile#L34

**Comment by KristianKalm** [comment]
@aldas 
I am aware yes. 

Unless we won't have better source soon, it seems I will have to do the manual work as well. 
Will fix/automate as much as I can in the weekend and then figure out the manual work.

**Comment by keeganmcbride** [comment]
OKEE has found someone else to maintain this repository. I will be stepping away, but I guess it will live on as an open source project and available at koroonakaart.ee

**Comment by solkmaaker** [comment]
Since koroonakaart.ee is back on the air, i'm closing  this issue.
Best of luck to @keeganmcbride to his future projects.
Let's keep politics separate from code.

**Comment by infokujur** [comment]
Shout out to people who have been involved or want to be involved.  . We have a lot of interest but no concrete thing. Let's get conversation going. Please drop us line > maarjaleena@okee.ee

**Comment by infokujur** [comment]
Or just comment #166
