### ISSUE TITLE
Ajaperioodi valik maakondadele

### ISSUE THREAD

**Issue by m6tlik** [koroonakaart/koroonakaart#189]
Nagu mõnel ülemisel graafikul, oleks vaja ajaperioodi valiku tööriista ka maakonaddele,
sest pikk madal joon ja Saaremaa kuskil alguses juba segavad viimaste trendide hindamist

**Comment by neuroactive** [comment]
@sarnane Many thanks for dealing with this.

I have made a couple of small improvement to the tooltip. I've right-aligning the numbers so that the digits can be more easily compared. I also tweaked the date format so that the leading "0" is dropped from the day of the month as it's a little more human-friendly like that.

![cases by county](https://user-images.githubusercontent.com/22959023/115750961-5f5e2680-a3a1-11eb-8cb9-7695123bf693.png)

**Comment by m6tlik** [comment]
Thanks
J
