### ISSUE TITLE
Filter incorrect vaccination data published by TEHIK

### ISSUE THREAD

**Issue by ProstoSanja** [koroonakaart/koroonakaart#198]
Apparently it is possible for them to publish two entries on the same day, with one containing completely false information.
![Screenshot_20210118-124004](https://user-images.githubusercontent.com/26527928/104904978-72b8ba80-598a-11eb-82f6-9ca91e5e7d35.png)

Potential solution: instead of choosing last row from vaccination data, we should choose one with latest date, and in case there are multiple, one with the biggest Total number?

**Comment by dorkster100** [comment]
This does not seem to be `completely false` data. Here is some additional information that was provided by TEHIK:

```
Kõigis andmestikes esineb ka vaktsineerimise staatus – VaccinationStatus andmeväli, kus hetkeseisuga esineb ainult „InProgress“ – seda seetõttu, et kasutusel on 2 doosiga Comiraty vaktsiin, kus teist doosi veel manustatud pole. Kui patsient on vaktsineerimiskuuri lõpetanud, st. Comiraty puhul saanud ka teise doosi, siis tekivad andmestikku vastavad VaccinationStaatus read „Completed“ olekuga. Juhul, kui võetakse kasutusele vaktsiinid, mille puhul on ette nähtud ainult 1 doosi manustamine, siis nende vaktsineerimiste käigus tekivad andmed otse „Completed“ staatuse alla. Eelnev tähendab, et Comiraty vaktsiiniga vaktsineeritute andmestikus hakkab teise doosi saamise tagajärjel „InProgress“ ridade juures arv vähenema ja „Completed“ staatuses arvud suurenema.
```

That means the InProgress are people who got vaccinated with 1 vaccine, which means one pending vaccination.

We could try to display this info in some way?

**Comment by rmkvi** [comment]
It would make sense to publish both InProgress and Complete numbers similarily to how TEHIK publishes it in Terviseamet koroonakaart because:
1. The prospect of single dose vaccines is unlikely in the near future. Current vaccines all are likely to comprise of multiple doses.
2. The Comirnaty vaccine gives quite high protection (around 80-85%?) already after 10 days from administering first dose and second dose after 21-27 days will raise it higher (ca 94%?).

Publishing only vaccinations with Complete status might be a bit misleading.

**Comment by Madis0** [comment]
How about "partly vaccinated" and "fully vaccinated"?
