### ISSUE TITLE
Cumulative cases per county over time

### ISSUE THREAD

**Issue by erik-heintare** [koroonakaart/koroonakaart#21]
Currently, the graph doesn't show how different counties are doing over time. Like, Saaremaa peaking and then slowing down.

**Comment by neuroactive** [comment]
Right, this is something we plan to add.

**Comment by keeganmcbride** [comment]
@PuuraJ

**Comment by dreambuilder123** [comment]
This is a great idea because many people are anxious to know about the situation of the county/counties where they/family or friends live (me included). 

What I'd like to suggest is relevant to this one - **New cases per day by county.** These two together will correspond to your current **"Cumulative cases"** and **"New cases per day"** at the **country** level.

Looking forward to the update!

**Comment by keeganmcbride** [comment]
I have added this into the app now.
