### ISSUE TITLE
Bug: Numbers of patients out of sync - header vr graph [reported by email]

### ISSUE THREAD

**Issue by infokujur** [koroonakaart/koroonakaart#210]
---
Paistab, et koroonakaart.ee ei näita graafikul haiglaravil viibivate patsientide arvu päris õigesti. Graafikul näitab, et haiglas on 558 inimest, lehe alguses ütleb, et 506. Lisasin ekraanitõmmised.
---  
image.png
![unnamed](https://user-images.githubusercontent.com/12999094/108356079-52338880-71f4-11eb-9467-f83c3f1acd3a.png)
![image](https://user-images.githubusercontent.com/12999094/108356082-5364b580-71f4-11eb-84a3-fc6f7d0f51f5.png)

**Comment by keeganmcbride** [comment]
Is OKEE still maintaining this repository? This issue has been reported already over a week ago now to @neuroactive and the fix is literally changing one variable in the python script. The issue is in: https://github.com/okestonia/koroonakaart/blob/29ccf4ffeb7e1b52f875b6d2ee861c14729154a3/TEHIK_Open_Data_Loading_Scripts/chart_data_functions.py#L18

hospitalizations += [int(result["Hospitalised"])]
activehospitalizations += [int(result["ActivelyHospitalised"])]

**Comment by keeganmcbride** [comment]
Not sure if this is still being actively maintained, but submitted the PR as the fix is no more than 2 seconds of work.

**Comment by dorkster100** [comment]
I am not sure what you want to imply by your comment, but as you know this project is maintained by volunteers, I myself am busy and sadly also sick. The issue that is reported here is not breaking, so it could wait until I am better and have some free time. However all commits are welcome, thank you for fixing this issue, I will test and merge.
