### ISSUE TITLE
Bug? Daily doses - mismatch with TA representation

### ISSUE THREAD

**Issue by infokujur** [koroonakaart/koroonakaart#213]
![ehgjljodeolffckf](https://user-images.githubusercontent.com/12999094/109814719-8026bd00-7c37-11eb-8d48-669114ea50f5.png)

**Comment by sarnane** [comment]
Hello!

"Kõik vaktsineeritud" shows the amount of all people who have been vaccinated (1 **or** 2 doses), but, on the top-left, Terviseamet shows the amount of doses administered (i.e when someone has gotten 2 doses, it has gone up by 2). koroonakaart.ee does not display the number of doses administered, but the amount of people vaccinated. That means, when someone gets their second dose, they get removed from "osaliselt vaktsineeritud" and added to "täielikult vaktsineeritud" (that's also why partially vaccinated per 24h can be negative), therefore, "kõik vaktsineeritud" does not change.

"24 h vähemalt üks kord vaksineeritud" is "kõik vaktsineeritud" because it shows the amount of people who have gotten at least 1 dose (i.e 1 **or** 2 doses).

IIRC, at least when I wrote the wrote the code for the vaccination bits, TEHIK does not publish the amount of people partially vaccinated. That is done by subtracting the amount of people completely vaccinated (24 h vaktsineerimiskuur lõpetatud, 2 doses) from all vaccinated 
("24 h vähemalt üks kord vaksineeritud", 1 **or** 2 doses), so, in that picture: 5215 - 2358 = 2857

This was recently changed (#206), [ERR reported on it](https://www.err.ee/1608091846/toimetus-selgitab-mis-muutus-vaktsineeritute-arvu-kajastamises).

That's how I understand it, but I could be mistaken. I hope this clears it up. If you have any questions, feel free to ask!

**Comment by infokujur** [comment]
It's all clear to me now. I'm closing it for now and it can be referred if same type of question will come.
