### ISSUE TITLE
I do not think, this is how vaccinations work

### ISSUE THREAD

**Issue by mikk150** [koroonakaart/koroonakaart#218]
From those numbers, if someone gets 2 shots, they immunize somebody else as well?

![image](https://user-images.githubusercontent.com/4953629/111775521-8c5a7d80-88b9-11eb-84b7-7f9d4551d13c.png)

So really `All Vaccinated` should be `Total shots given`

**Comment by neuroactive** [comment]
I believe it's correct as it stands.

"All vaccinated" refers to the total number of people who have received at least one shot. The wording in English isn't very clear, and should probably be changed to "Individuals vaccinated" or "Total people vaccinated".

The figures are correct because the number of people who have had 1 shot plus the number of people who have had 2 shots equals the "All vaccinated" figure. Bear in mind that the figures for the number of people who have had 1 shot and 2 shots are exclusive, that is to say that when someone has their second shot, the number of people who are listed as having one shot decreases by one, at the same time as the number of people who have had two shots increases by one.

The calculation for the total number of shots administered is the number of people who have had 1 shot (102,717) plus two times the number of people who have had 2 shots (2 x 54,772 = 109,544), which gives a total of 212,261 shots.

"All vaccinated from eligible population" would probably be better worded in English as "Total vaccinated from eligible population".

So unless anyone has any further comments, I will close this issue shortly.

**Comment by mikk150** [comment]
So, I should see `Partially vaccinated` plaetou or even get less over time?

**Comment by neuroactive** [comment]
Yes, the partially vaccinated figure should eventually fall as people move into the completely vaccinated category. Whether it goes up or down in the short term depends on whether more people are getting their first shot than are getting their second one. There will always be some people who don't complete the full course of shots though, so the partially vaccinated figure won't fall to zero.
