### ISSUE TITLE
add doubling prognosis in days and trends

### ISSUE THREAD

**Issue by whysthatso** [koroonakaart/koroonakaart#34]
a feature i’ve seen for a quick grasp of trends is to add the number of days until infections will double. then you can add a trend indicator (slowing down, speeding up, staying steady)

**Comment by kunstnik** [comment]
How long will be the base of the speed calculation? 5, 10 or 20 days? To forecast local (County's or Estonian) doubling time.
Because the doubling speed is highly variable. The more narrow base you take, the more bumping up and down you get the doubling time (and speed). Actually you could insert the doubling time to the logarithmic scale as a function of horizontal lines at ~0,29 of the distance between lines, at the moment lines mean tenfolding. 
![sketch-1585544787135 png](https://user-images.githubusercontent.com/62639296/77877121-84936a80-725d-11ea-8671-9778034377e2.jpg)
![sketch-1585545707573 png](https://user-images.githubusercontent.com/62639296/77877950-dc32d580-725f-11ea-811d-ed8fc2d9678d.jpg)
So we could show the speeds as slope lines at certain angle on logarithmic chart, where the angle depends on scaling of both axis (even turning of mobile device changes these angles). When to join the sloped lines to a point , we get a scale, "reverse speedometer". Triggering event should be earlier of sharp change in the speed by incubation period+getting test results+putting data into chart, 3-4+3+1=~5-7days: https://www.worldometers.info/coronavirus/coronavirus-incubation-period/
This is actually a new issue (not maintenance issue). #73
![sketch-1585550812107 png](https://user-images.githubusercontent.com/62639296/77883351-a0057200-726b-11ea-8523-33def36f80f0.jpg)

**Comment by keeganmcbride** [comment]
This is a feature we do not currently plan on adding, so will close for now.

**Comment by whysthatso** [comment]
not sure why this is closed. shouldn't it stay open for future reference, independent of your planning process?
