### ISSUE TITLE
Number of confirmed tests was moved to yesterday. 

### ISSUE THREAD

**Issue by blinchk** [koroonakaart/koroonakaart#86]
![Screenshot_2020-04-02-23-01-28-972_com opera touch](https://user-images.githubusercontent.com/49353043/78296250-0ae9ce00-7536-11ea-89e2-2157908d7533.jpg)
Hello!

How you can see on the screenshot, number of positive results of April 2nd shows as April 1st data.

**Comment by keeganmcbride** [comment]
The issue here is with how TEHIK releases data and a bit of confusing communication from Terviseamet. All numbers published by TA, actually represent yesterday's stats. So, all data needed to be shifted back one day. Additionally there were some issues with timestamps (data for yesterday would also include tests registered between mdinight and 7am today). So, TEHIK has created a new datapoint called "StatisticsDate", which corrects this. We now use this date as well in our map.
