### ISSUE TITLE
Definition of "Recovered"

### ISSUE THREAD

**Issue by VeryTemporary** [koroonakaart/koroonakaart#89]
How is "recovered" defined? Please add a note to the chart. Does "recovered" include only hospitalised cases who are discharged? Is it only those who have tested negative after a positive test? How are people who test positive and then self isolate with no hospitalisation removed from the "active" cases?

"Recovered" seems very low given that here were 121 active cases 3 weeks ago.

**Comment by Kypsis** [comment]
Recovered is currently only hospitalised cases who recovered and were discharged. As was mentioned in today's press conference the government is working on technical solution to relay the actual recovered number.

**Comment by clyde-johnston** [comment]
It would be better to call it "Discharged" rather than "Recovered".  I would add a total for "Hospitalised" or "Admitted" and group it with "In treatment", "Deaths" and "Discharged", where "Hospitalised" is the sum of these three.
Getting figures for "recovered" and "deaths" for people who were not hospitalised may be hard to track on a daily basis.  Better to stick to what we know.

**Comment by keeganmcbride** [comment]
Terviseamet changed their wording to make it clear that it is not recovered, but rather just released from the hospital. We have updated our application to reflect this change and also removed active cases for the time being as it is not clear how many patients have recovered, in the sense that they have no symptoms or have given a negative test.
