### ISSUE TITLE
Active cases trend line

### ISSUE THREAD

**Issue by maxml76** [koroonakaart/koroonakaart#98]
I would like to see active cases trend line

**Comment by iNikem** [comment]
Why "Cases" chart does not have a line for "Active cases" with daily values?

**Comment by keeganmcbride** [comment]
Can add this in, shouldn't be a problem, sorry have been so slow with updates, but I will try to get to it. If someone wants to take the initiative it would be appreciated.

**Comment by m6tlik** [comment]
There is an option to generate the number of potentially infective people. 
As I was interested on regions, I estimated it from cumulative estimates. But you can use also daily positives. 
There is clever to add also an selectable option for different infectivity periods. I made it for 10 and 14 days.
There you see that Harjumaa has constant level, others improve or have recovered from infectivity
[koroona_14p_haiged.xlsx](https://github.com/okestonia/koroonakaart/files/4521121/koroona_14p_haiged.xlsx)
[koroona_10p_haiged.xlsx](https://github.com/okestonia/koroonakaart/files/4521122/koroona_10p_haiged.xlsx)

**Comment by keeganmcbride** [comment]
Hi @m6tlik I actually thought about doing it the same way, but we decided against it ultimately. If we were to do this, we should use the ResultTime variable instead of StatisticsDate from TEHIK, but there is an issue also that this 14 day period is from when symptoms start rather than when the test is confirmed. There is still quite many unknowns and while it may provide a good estimation, we didn't feel comfortable putting it up at the moment. Though this may change in the future if new data is available or we can find some scientific papers backing up active case estimation.

**Comment by m6tlik** [comment]
Hi,
Epidemic is based on noisy data anyway, and one has to deal with the data available (not having information is even worse, as in present in many discussions). Measurement error as the infection-time vs positive-test-time are correlated proxies, the best what one can ever get. The current relaxation discussion is about, whether the status is dangerous or not, but presently available graphics do not help. The probability of infectivity would be the best, however, this has too many unknown parameters. The # of potentially still infective or being-sick persons from their positive-test date is good-enough proxy. To make sure that users of the graph would not stick to precise input data, therefore there is need for this extra selection of day 5, 10, 14, 20. Then every body can take its own decision based on available literature, and also test for the sensitivity/quality.issues of the estimate.

**Comment by keeganmcbride** [comment]
We have now added in a rough estimate to the site. It pretty much works as you wrote, just take todays date and remove all cases that occured fourteen days before it. It is a _rough_ estimate, but since Postimees also put it up and that was signed off on some of the scientists advising gov we decided to put it up as well.

**Comment by m6tlik** [comment]
Great! Apologies, I had a formula error in these files anyway - two ideas in one (as there were source options). Could you consider to produce the same prediction figure per county (after cumulative version), as then one can see that in present moment, Tallinn and Pärnu and Tartu are problematic ones, other improved or in progress.

**Comment by keeganmcbride** [comment]
We have added in now also an estimate for daily county active cases.

**Comment by m6tlik** [comment]
Thanks! There is to think about now ;)
